export default {
  name: "theme-rebass-ts",
  version: "2.0.0-0",
  library: "styled-components",
  librarytype: "iopa-compositor",
  libraryversion: "1.0.0",
  components: [
    require('./elements/Arrow').default,
    require('./elements/Avatar').default,
    require('./elements/BackgroundImage').default,
    require('./elements/Badge').default,
    require('./elements/Banner').default,
    require('./elements/BlockLink').default,
    require('./elements/Blockquote').default,
    require('./elements/Border').default,
    require('./elements/Button').default,
    require('./elements/ButtonCircle').default,
    require('./elements/ButtonOutline').default,
    require('./elements/ButtonTransparent').default,
    require('./elements/Caps').default,
    require('./elements/Card').default,
    require('./elements/Carousel').default,
    require('./elements/Checkbox').default,
    require('./elements/Circle').default,
    require('./elements/Close').default,
    require('./elements/Code').default,
    require('./elements/Column').default,
    require('./elements/Container').default,
    require('./elements/Divider').default,
    require('./elements/Dot').default,
    require('./elements/Drawer').default,
    require('./elements/Embed').default,
    require('./elements/Group').default,
    require('./elements/Heading').default,
    require('./elements/Image').default,
    require('./elements/Input').default,
    require('./elements/Label').default,
    require('./elements/Lead').default,
    require('./elements/Link').default,
    require('./elements/Measure').default,
    require('./elements/Message').default,
    require('./elements/Modal').default,
    require('./elements/NavLink').default,
    require('./elements/Panel').default,
    require('./elements/PanelFooter').default,
    require('./elements/PanelHeader').default,
    require('./elements/Position').default,
    require('./elements/Pre').default,
    require('./elements/Progress').default,
    require('./elements/Radio').default,
    require('./elements/Root').default,
    require('./elements/Row').default,
    require('./elements/Select').default,
    require('./elements/Slider').default,
    require('./elements/Small').default,
    require('./elements/Subhead').default,
    require('./elements/Switch').default,
    require('./elements/Tab').default,
    require('./elements/Tabs').default,
    require('./elements/Text').default,
    require('./elements/Textarea').default,
    require('./elements/Toolbar').default,
    require('./elements/Tooltip').default,
    require('./elements/Truncate').default
  ]
}